"""initial models

Revision ID: 908464950add
Revises: 
Create Date: 2026-04-16 13:56:50.537866
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "908464950add"
down_revision = None
branch_labels = None
depends_on = None

skill_level_enum = postgresql.ENUM(
    "BEGINNER",
    "INTERMEDIATE",
    "ADVANCED",
    name="skill_level_enum",
    create_type=False,
)
input_type_enum = postgresql.ENUM(
    "UPLOAD",
    "LIVE",
    name="input_type_enum",
    create_type=False,
)
session_status_enum = postgresql.ENUM(
    "ACTIVE",
    "COMPLETED",
    "ABORTED",
    name="session_status_enum",
    create_type=False,
)
severity_level_enum = postgresql.ENUM(
    "MINOR",
    "MODERATE",
    "SEVERE",
    name="severity_level_enum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    skill_level_enum.create(bind, checkfirst=True)
    input_type_enum.create(bind, checkfirst=True)
    session_status_enum.create(bind, checkfirst=True)
    severity_level_enum.create(bind, checkfirst=True)

    op.create_table('metric_types',
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_types')),
    sa.UniqueConstraint('metric_name', name=op.f('uq_metric_types_metric_name'))
    )
    op.create_table('sports',
    sa.Column('sport_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sports')),
    sa.UniqueConstraint('sport_name', name=op.f('uq_sports_sport_name'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drills',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('drill_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', skill_level_enum, nullable=False),
    sa.Column('reference_payload', sa.JSON(), nullable=False),
    sa.Column('coaching_rules', sa.JSON(), nullable=False),
    sa.Column('target_metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_drills_sport_id_sports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drills'))
    )
    op.create_index(op.f('ix_drills_sport_id'), 'drills', ['sport_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skill_level', skill_level_enum, nullable=False),
    sa.Column('injury_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_user_profiles_sport_id_sports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('training_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drill_id', sa.UUID(), nullable=False),
    sa.Column('input_type', input_type_enum, nullable=False),
    sa.Column('status', session_status_enum, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drill_id'], ['drills.id'], name=op.f('fk_training_sessions_drill_id_drills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions'))
    )
    op.create_index(op.f('ix_training_sessions_drill_id'), 'training_sessions', ['drill_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('severity_level', severity_level_enum, nullable=False),
    sa.Column('technique_issue', sa.Text(), nullable=False),
    sa.Column('coaching_cue', sa.Text(), nullable=False),
    sa.Column('metric_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_feedback_session_id_training_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('overall_accuracy', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_session_summaries_session_id_training_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_summaries')),
    sa.UniqueConstraint('session_id', name=op.f('uq_session_summaries_session_id'))
    )
    op.create_table('progress_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_types.id'], name=op.f('fk_progress_records_metric_id_metric_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['summary_id'], ['session_summaries.id'], name=op.f('fk_progress_records_summary_id_session_summaries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_records'))
    )
    op.create_index(op.f('ix_progress_records_metric_id'), 'progress_records', ['metric_id'], unique=False)
    op.create_index(op.f('ix_progress_records_summary_id'), 'progress_records', ['summary_id'], unique=False)
    op.create_index(op.f('ix_progress_records_user_id'), 'progress_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_progress_records_user_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_summary_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_metric_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_drill_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_drills_sport_id'), table_name='drills')
    op.drop_table('drills')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sports')
    op.drop_table('metric_types')
    severity_level_enum.drop(bind, checkfirst=True)
    session_status_enum.drop(bind, checkfirst=True)
    input_type_enum.drop(bind, checkfirst=True)
    skill_level_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
