from __future__ import annotations

METRIC_TYPE_SEEDS = [
    {"metric_name": "posture_accuracy", "metric_unit": "percent"},
    {"metric_name": "knee_alignment_score", "metric_unit": "alignment_score"},
    {"metric_name": "squat_depth", "metric_unit": "depth_score"},
    {"metric_name": "elbow_angle_consistency", "metric_unit": "consistency_index"},
    {"metric_name": "balance_stability", "metric_unit": "stability_score"},
    {"metric_name": "torso_alignment", "metric_unit": "alignment_score"},
    {"metric_name": "repetition_consistency", "metric_unit": "consistency_index"},
    {"metric_name": "hip_stability", "metric_unit": "stability_score"},
    {"metric_name": "shoulder_control", "metric_unit": "control_score"},
    {"metric_name": "shooting_alignment", "metric_unit": "alignment_score"},
    {"metric_name": "stance_width_control", "metric_unit": "control_score"},
    {"metric_name": "elbow_extension", "metric_unit": "extension_score"},
    {"metric_name": "wrist_elbow_alignment", "metric_unit": "alignment_score"},
    {"metric_name": "lockout_control", "metric_unit": "control_score"},
    {"metric_name": "shoulder_symmetry", "metric_unit": "symmetry_score"},
    {"metric_name": "knee_flexion", "metric_unit": "flexion_score"},
    {"metric_name": "hip_level_stability", "metric_unit": "stability_score"},
    {"metric_name": "plant_foot_alignment_ratio", "metric_unit": "alignment_score"},
    {"metric_name": "instep_backswing_knee_angle", "metric_unit": "angle_score"},
    {"metric_name": "instep_contact_extension", "metric_unit": "extension_score"},
    {"metric_name": "instep_torso_tilt", "metric_unit": "tilt_score"},
    {"metric_name": "instep_follow_through_stability", "metric_unit": "stability_score"},
    {"metric_name": "support_foot_distance_ratio", "metric_unit": "distance_ratio_score"},
    {"metric_name": "shooting_knee_load", "metric_unit": "flexion_score"},
    {"metric_name": "shooting_swing_velocity", "metric_unit": "velocity_proxy_score"},
    {"metric_name": "shooting_contact_extension", "metric_unit": "extension_score"},
    {"metric_name": "torso_rotation_stability", "metric_unit": "stability_score"},
    {"metric_name": "shooting_balance", "metric_unit": "balance_score"},
]
